apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: some-app
  template:
    metadata:
      labels:
        app: some-app
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.26.0
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: content
          configMap:
            name: some-app-content
