apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: some-app
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: some-app
  namespace: some-app
spec:
  subscriptions:
    - image:
        repoURL: public.ecr.aws/nginx/nginx
        semverConstraint: ^1.26.0
        discoveryLimit: 5
---
