apiVersion: v1
kind: Service
metadata:
  name: some-app
spec:
  type: NodePort
  selector:
    app: some-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: placeholder
