apiVersion: v1
kind: ConfigMap
metadata:
  name: some-app-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>uat</title>
    </head>
    <body>

    <h1>uat</h1>
    some-app

    </body>
    </html>
