---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: some-app
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: some-app
      sources:
        stages:
          - test
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: ${GITOPS_REPO_URL}
            checkout:
              - branch: main
                path: ./src
              - branch: stage/uat
                create: true
                path: ./out
        - uses: git-clear
          config:
            path: ./out
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/base
            images:
              - image: public.ecr.aws/nginx/nginx
        - uses: kustomize-build
          config:
            path: ./src/stages/test
            outPath: ./out/manifests.yaml
        - uses: git-commit
          as: commit
          config:
            path: ./out
            messageFromSteps:
              - update-image
        - uses: git-push
          config:
            path: ./out
            targetBranch: stage/uat
        - uses: argocd-update
          config:
            apps:
              - name: some-app-uat
                sources:
                  - repoURL: ${GITOPS_REPO_URL}
                    desiredCommitFromStep: commit
---
