apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - kargo.yaml

patches:
  - target:
      kind: Service
      name: some-app
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30083
